// let chinese = [
//   { name: "夜空中最亮的星 | The Brightest Star in the Night Sky", duration: "3:30"},
//   { name: "You Took My Heart Away", duration: "2:45" },
//   { name: "我的秘密 | My Secret", duration: "4:15" },
//   { name: "喜欢你 | Like You (Beyond cover)", duration: "3:00", extra: 'holidays'},
//   { name: "少年 | Shao Nian | Youngster", duration: "5:20", extra: 'holidays'},
//   { name: "突然想起你 | Suddenly Thinking of you", duration: "3:50" },
//   { name: "你的酒馆对我打了烊 | Your Bar is Close to Me", duration: "2:15" },
//   { name: "爱不爱我 | Do You love Me", duration: "4:10" },
//   { name: "情深深雨濛濛 | Rain", duration: "2:30" },
//   { name: "后来 | Afterwards", duration: "3:25" },
//   { name: "东西 | Things", duration: "4:55" },
//   { name: "Mojito", duration: "2:40" },
//   { name: "海阔天空 | The Whole Wide World", duration: "5:05", extra: 'holidays' },
//   { name: "你一定要幸福 | Happiness", duration: "3:15" },
//   { name: "I Love You", duration: "4:40" },
//   { name: "一生听爱 ｜ Life is listening to love", duration: "2:20" },
//   { name: "不再犹豫 ｜No longer hesitate", duration: "3:35" },
//   { name: "让我欢喜让我忧| Make Me Happy, Make Me Worry", duration: "4:25" },
//   { name: "改变自己 | Change Yourself", duration: "2:55" },
//   { name: "讲真的 | Tell the Truth", duration: "5:10" },
//   { name: "自然醒  | Woke Up", duration: "5:05" },
//   { name: "大风吹 | The Wind Blows", duration: "3:15" },
//   { name: "红色高跟鞋 | Red High Heels", duration: "4:40" },
//   { name: "甄魔鬼中的天使 | The Devil From Heaven", duration: "2:20" },
//   { name: "月亮代表我的心 | Moon Heart", duration: "3:35" },
//   { name: "隐形的翅膀 | Invisible Wings", duration: "4:25" },
//   { name: "爱就一个字| Love is just a Word", duration: "2:55" },
//   { name: "嘉宾 | Guest", duration: "5:10" },
//   { name: "Cookie Can", duration: "5:05" },
//   { name: "但愿人长久 | Long Live", duration: "3:15" },
//   { name: "失恋阵线联盟 | Lost love Alliance", duration: "4:40" },
//   { name: "你的答案 | Your answer", duration: "2:20" },
//   { name: "⽉半⼩夜曲 | Moon Serenade", duration: "3:35" },
//   { name: "恭喜发财 | Gong Xi Fa Cai", duration: "4:25", extra: 'chinNewYear' },
//   { name: "说散就散 | If you say you leave", duration: "2:55" },
//   { name: "恋爱ing | LOVE-ing", duration: "5:10" },
//   { name: "愛要坦蕩蕩 | Love must be generous", duration: "5:05" },
//   { name: "漠河舞厅  | MoHe Ballroom", duration: "3:15" },
//   { name: "张国荣 (Leslie Cheung) — Monica", duration: "4:40" },
//   { name: "张敬轩 — 只是太爱你 （Love you so much）", duration: "2:20" },
//   { name: "陳奕迅 (Eason Chan) —  孤勇者 （Lonely Warrior）", duration: "3:35", extra: 'holidays' },
//   { name: "Mike — 初恋 （First love）", duration: "4:25" },
//   { name: "周蕙 — 不想让你知道（Don’t want you to know）", duration: "2:55" },
//   { name: "韩红 — 青春（Youth）", duration: "2:30" },
//   { name: "老狼 — 同桌的你 （My deskmate）", duration: "3:42" },
//   { name: "许冠杰 — 財神到 （Coi San Dou， 春节 special）", duration: "4:54", extra: 'chinNewYear' },
//   { name: "新裤子 —  你要跳舞吗 （Do you want to dance?)", duration: "6:06" },
//   { name: "张艾嘉 — 爱的代价 (The price of love)", duration: "7:18" },
//   { name: "梦然 — 是你 （Shi Ni)", duration: "8:30" },
//   { name: "G.E.M. — 光年之外 （Light years away）", duration: "9:42" },
//   { name: "告五人 (Accusefive) — 爱人错过 （Somewhere in time）", duration: "10:54" },
// ];


